import Head from "next/head";
import type { NextPage } from "next";
import { useRouter } from "next/router";

import { Button } from "@/components/elements";

const HomePage: NextPage = () => {
  const router = useRouter();

  return (
    <div className={""}>
      <Head>
        <title>Buy Me Coffee</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <div>Landing page</div>
        <div>
          <Button onClick={() => router.push("/random")}>random profile</Button>
        </div>
      </div>
    </div>
  );
};

export default HomePage;
