import Head from "next/head";
import type { NextPage } from "next";
import { useRouter } from "next/router";

import { useContract, useSigner } from "wagmi";

import contracts from "@/contracts/hardhat_contracts.json";
import { NETWORK_ID } from "@/config";

import { Button } from "@/components/elements";
import { SelectProfile } from "@/components/profile";

const HomePage: NextPage = () => {
  const router = useRouter();
  const chainId = Number(NETWORK_ID);
  const { data: signerData } = useSigner();

  const allContracts = contracts as any;
  const factoryAddress =
    allContracts[chainId][0].contracts.CoffeeFactory.address;
  const factoryABI = allContracts[chainId][0].contracts.CoffeeFactory.abi;

  const factoryContract = useContract({
    addressOrName: factoryAddress,
    contractInterface: factoryABI,
    signerOrProvider: signerData,
  });

  // console.log("factoryContract", factoryContract);

  const handleCreate = async (name: string) => {
    console.log("handleCreate");
    const tx = await factoryContract.createCoffeeContract(name);
    tx.wait(1).then((res: any) => {
      // console.log("res", res);
    });
  };

  const handleGetNumber = async () => {
    console.log("handleGetNumber");
    console.log(factoryContract);
    try {
      const tx = await factoryContract.numCoffeeContracts();
      console.log("tx", tx);
      const contract = await factoryContract.allCoffeeContracts(0);
      console.log("contract", contract);
      const contract2 = await factoryContract.allCoffeeContracts(1);
      console.log("contract2", contract2);
    } catch (e) {
      console.log("e", e);
    }
  };

  const handleGetHandle = async () => {
    console.log("handleGetHandle");
    const tx = await factoryContract.searchHandles("newthing");
    console.log("tx", tx);
    const tx2 = await factoryContract.searchHandles("anotherthing");
    console.log("tx2", tx2);
  };

  return (
    <div className={""}>
      <Head>
        <title>Buy Me Coffee</title>
        <meta name="description" content="Generated by npx create-web3" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap">
        <div className="m-8">
          <Button onClick={() => router.push("/random")}>random profile</Button>
        </div>
        <div className="m-8">
          <Button onClick={() => router.push("/newthing")}>
            goto newthing
          </Button>
        </div>
        <div className="m-8">
          <Button onClick={() => router.push("/anotherthing")}>
            goto anotherthing
          </Button>
        </div>
        <div className="m-8">
          <Button onClick={() => handleCreate("newthing")}>
            create newthing
          </Button>
        </div>
        <div className="m-8">
          <Button onClick={() => handleCreate("anotherthing")}>
            create anotherthing
          </Button>
        </div>
        <div className="m-8">
          <Button onClick={() => handleGetNumber()}>number of contracts</Button>
        </div>
        <div className="m-8">
          <Button onClick={() => handleGetHandle()}>check handles</Button>
        </div>
      </div>
      <SelectProfile />
    </div>
  );
};

export default HomePage;
